### ISSUE TITLE
install.sh should always install latest executable 

### ISSUE THREAD

**Issue by bilgehannal** [bilgehannal/foldercode-cli#1]
* if there is a new release, we should update the install.sh with the latest release tag.

Here is requirements:
* install.sh should determine the latest release version
* when a user install fcode using install.sh, latest fcode version should be downloaded

**Comment by emrullahcirit** [comment]
I implemented this feature. 
Can you please review my [PR](https://github.com/bilgehannal/foldercode-cli/pull/3)?

**Comment by bilgehannal** [comment]
> I implemented this feature. Can you please review my [PR](https://github.com/bilgehannal/foldercode-cli/pull/3)?

Hello,
Thanks for the contribution,
I tried to run the version getting command below on linux and mac
`curl https://api.github.com/repos/bilgehannal/foldercode-cli/releases/latest|grep '"tag_name": '|cut -d 'v' -f 2|cut -d '"' -f 1`
* Unfortunately, it is not running on MacOS, it should be run on MacOS also.
* Can we use wget instead of curl. Reason is below:
    * wget is more basic tool, some linux distros may have wget as opposed to curl
    * wget is using in installing, in the installing.sh, lets keep using wget, using two different tool for same purpose increases the dependency.

**Comment by bilgehannal** [comment]
Hello, thanks for your contribution, I wrote a comment :)

**Comment by emrullahcirit** [comment]
thank you for your feedback, can you check pr again :)

**Comment by bilgehannal** [comment]
After merging, I am going to close this issue, thanks.

**Comment by bilgehannal** [comment]
v1.0.1 is active now
